# Exploring grad rates

In [27]:
import pandas as pd
import numpy as np

In [14]:
diplomas=pd.read_csv('Diplomas-and-Completion.csv',skiprows=3,skipfooter=1)
diplomas

/var/folders/p9/9vqlyg213v3b9h9zrksgz6z00000gn/T/ipykernel_12384/2260140521.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  diplomas=pd.read_csv('Diplomas-and-Completion.csv',skiprows=3,skipfooter=1)

,Student Subgroup,Advanced Diplomas,Standard Diplomas,Other Diplomas,GED's,Dropouts,Other Non-Graduates
0,All Students,50354,39349,1875,907,4438,1716
1,Female,27408,17323,610,350,1645,701
2,Male,22886,21945,1263,556,2789,1012
3,American Indian,108,117,5,4,10,3
4,Asian,6025,1443,97,16,68,35
5,Black,8111,10540,640,225,1119,707
6,Hispanic,7130,8367,270,133,1858,359
7,Native Hawaiian,97,61,3,3,2,2
8,White,25871,16565,763,464,1211,504
9,Multiple Races,3012,2256,97,62,170,106
10,Students with Disabilities,1430,7462,1875,125,868,115
11,Economically Disadvantaged,12779,21123,1108,494,2352,1214
12,English Learners,1583,4224,267,26,1427,150
13,Migrant,<,<,<,<,0,<
14,Homeless,197,699,48,29,170,78
15,Military Connected,2527,1493,44,18,52,30
16,Foster Care,22,180,23,11,85,24

In [9]:
diplomas['Student Subgroup'].value_counts()

Student Subgroup
All Students                                                                                                                                                                             1
Female                                                                                                                                                                                   1
Foster Care                                                                                                                                                                              1
Military Connected                                                                                                                                                                       1
Homeless                                                                                                                                                                                 1
Migrant                                                                                                                                                                                  1
English Learners                                                                                                                                                                         1
Economically Disadvantaged                                                                                                                                                               1
Students with Disabilities                                                                                                                                                               1
Multiple Races                                                                                                                                                                           1
White                                                                                                                                                                                    1
Native Hawaiian                                                                                                                                                                          1
Hispanic                                                                                                                                                                                 1
Black                                                                                                                                                                                    1
Asian                                                                                                                                                                                    1
American Indian                                                                                                                                                                          1
Male                                                                                                                                                                                     1
\r\n                  < = A group below state definition for personally identifiable results\r\n- = Not applicable or no data for group\r\n* = Data not yet available                    1
Name: count, dtype: int64

In [18]:
diplomas.dtypes

Student Subgroup       object
Advanced Diplomas      object
Standard Diplomas      object
Other Diplomas         object
GED's                  object
Dropouts                int64
Other Non-Graduates    object
dtype: object

In [23]:
diplomas.index

RangeIndex(start=0, stop=17, step=1)

In [29]:
diplomas.loc[13].replace('<',np.nan,inplace=True)
diplomas

/var/folders/p9/9vqlyg213v3b9h9zrksgz6z00000gn/T/ipykernel_12384/1225848089.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  diplomas.loc[13].replace('<',np.nan,inplace=True)

,Student Subgroup,Advanced Diplomas,Standard Diplomas,Other Diplomas,GED's,Dropouts,Other Non-Graduates
0,All Students,50354,39349,1875,907,4438,1716
1,Female,27408,17323,610,350,1645,701
2,Male,22886,21945,1263,556,2789,1012
3,American Indian,108,117,5,4,10,3
4,Asian,6025,1443,97,16,68,35
5,Black,8111,10540,640,225,1119,707
6,Hispanic,7130,8367,270,133,1858,359
7,Native Hawaiian,97,61,3,3,2,2
8,White,25871,16565,763,464,1211,504
9,Multiple Races,3012,2256,97,62,170,106
10,Students with Disabilities,1430,7462,1875,125,868,115
11,Economically Disadvantaged,12779,21123,1108,494,2352,1214
12,English Learners,1583,4224,267,26,1427,150
13,Migrant,<,<,<,<,0,<
14,Homeless,197,699,48,29,170,78
15,Military Connected,2527,1493,44,18,52,30
16,Foster Care,22,180,23,11,85,24